customCommands:
  containers:
    - name: "Valkey: Create Cluster"
      command: "valkey-cli -a passwd --cluster create 127.0.0.1:6380 127.0.0.1:6381 127.0.0.1:6382 127.0.0.1:6383 127.0.0.1:6384 127.0.0.1:6385 --cluster-replicas 1"
      description: "在 Host 模式下快速初始化集群"
      attach: true
